version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      docusaurus:
        patterns:
          - "@docusaurus/*"
    ignore:
      - dependency-name: "@docusaurus/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
