name: check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Corepack enable
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Typecheck
        run: yarn typecheck

      - name: Build application
        run: yarn build
        env:
          CI: true
